# Generated by Django 6.0.7 on 2026-07-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('seri_no', models.CharField(max_length=150, verbose_name='Seri No')),
                ('giris_tarihi', models.DateField(verbose_name='Giriş Tarihi')),
                ('adet', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StokHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_turu', models.CharField(choices=[('giris', 'Stok Girişi'), ('cikis', 'Stok Çıkışı'), ('duzenleme', 'Ürün Düzenleme')], max_length=20)),
                ('miktar', models.IntegerField()),
                ('aciklama', models.CharField(blank=True, max_length=300)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='stok.urun')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-tarih'],
            },
        ),
    ]
