# Generated by Django 6.0.7 on 2026-07-16 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stokhareketi',
            name='islem_turu',
            field=models.CharField(choices=[('giris', 'Stok Girişi'), ('cikis', 'Stok Çıkışı'), ('duzenleme', 'Ürün Düzenleme'), ('firma_gonderisi', 'Firma Gönderisi'), ('firma_donusu', 'Firma Dönüşü')], max_length=20),
        ),
        migrations.CreateModel(
            name='FirmaGonderi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('gonderim_tarihi', models.DateField(verbose_name='Gönderim Tarihi')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firma_gonderileri', to='stok.urun')),
            ],
            options={
                'verbose_name': 'Firma Gönderisi',
                'verbose_name_plural': 'Firma Gönderileri',
                'ordering': ['-gonderim_tarihi', '-id'],
            },
        ),
    ]
