# Generated by Django 6.0.7 on 2026-07-16 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0002_alter_stokhareketi_islem_turu_firmagonderi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmagonderi',
            name='urun',
        ),
        migrations.AddField(
            model_name='firmagonderi',
            name='seri_no',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Seri No'),
        ),
        migrations.AddField(
            model_name='firmagonderi',
            name='stok_urunu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_gonderileri', to='stok.urun', verbose_name='Stoktan Seç'),
        ),
        migrations.AddField(
            model_name='firmagonderi',
            name='urun_adi',
            field=models.CharField(default='', max_length=200, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='stokhareketi',
            name='islem_turu',
            field=models.CharField(choices=[('giris', 'Stok Girişi'), ('cikis', 'Stok Çıkışı'), ('duzenleme', 'Ürün Düzenleme'), ('firma_gonderisi', 'Firma Gönderisi'), ('firma_donusu', 'Firma Dönüşü')], max_length=30),
        ),
    ]
