# Generated by Django 6.0.7 on 2026-07-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0003_remove_firmagonderi_urun_firmagonderi_seri_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCihaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('seri_no', models.CharField(max_length=150, verbose_name='Seri No')),
            ],
            options={
                'verbose_name': 'Demo Cihaz',
                'verbose_name_plural': 'Demo Cihazlar',
                'ordering': ['urun_adi', 'seri_no'],
            },
        ),
    ]
