# Generated by Django 6.0.7 on 2026-07-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0004_democihaz'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteriSenseKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bayi', models.CharField(max_length=200, verbose_name='Bayi')),
                ('firma', models.CharField(max_length=200, verbose_name='Firma')),
                ('urun_adi', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('seri_no', models.CharField(max_length=150, verbose_name='Seri No')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'SteriSense Kaydı',
                'verbose_name_plural': 'SteriSense Kayıtları',
                'ordering': ['-tarih', '-id'],
            },
        ),
    ]
